export const ReconstructionActionTypes = {
  INIT_RECONSTRUCTION_STATE: 'RECONSTRUCTION:INIT_RECONSTRUCTION_STATE',
  SET_MESSAGE: 'RECONSTRUCTION:SET_MESSAGE',
  APPEND_SHARE: 'RECONSTRUCTION:APPEND_SHARE',
} as const
