export const ReconstructionActionTypes = {
  INIT_RECONSTRUCTION_STATE: 'RECONSTRUCTION:INIT_RECONSTRUCTION_STATE',
  SET_MESSAGE: 'RECONSTRUCTION:SET_MESSAGE',
  SET_SHARES: 'RECONSTRUCTION:SET_SHARES',
  APPEND_SHARE_FROM_TEXT: 'RECONSTRUCTION:APPEND_SHARE_FROM_TEXT',
  CHANGE_ISREADY: 'RECONSTRUCTION:CHANGE_ISREADY',
} as const
