export const SharingActionTypes = {
  INIT_SHARING_STATE: 'SHARING:INIT_SHARING_STATE',
  SET_COUNTER: 'SHARING:SET_COUNTER',
  DECREMENT_COUNTER: 'SHARING:DECREMENT_COUNTER',
  START_SHARING: 'SHARING:START_SHARING',
  END_SHARING: 'SHARING:END_SHARING',
} as const
