export const SharingActionTypes = {
  INIT_SHARING_STATE: 'SHARING:INIT_SHARING_STATE',
  SET_MESSAGE: 'SHARING:SET_MESSAGE',
  SET_SHARES: 'SHARING:SET_SHARES',
  SET_COUNTER: 'SHARING:SET_COUNTER',
  DECREMENT_COUNTER: 'SHARING:DECREMENT_COUNTER',
} as const
